
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 30 23:23:31 CET 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int IDENTIFIER = 67;
  public static final int GT = 21;
  public static final int POINT_MEMORYACCESS = 4;
  public static final int TYPE = 59;
  public static final int PLUS_EQ = 27;
  public static final int FUNCTION_CALL = 2;
  public static final int GE = 23;
  public static final int MULT_OR_MEMORYACCESS = 37;
  public static final int INCR = 34;
  public static final int ANDBIT_OR_MEMORYACCESS = 12;
  public static final int COMMA = 61;
  public static final int FLOAT_TYPE = 45;
  public static final int POINTER_OR_XOR = 48;
  public static final int LT = 20;
  public static final int MOD_EQ = 32;
  public static final int INTEGER_LITERAL = 70;
  public static final int NOT = 19;
  public static final int LE = 22;
  public static final int DECR = 35;
  public static final int BOOLEAN_TYPE = 46;
  public static final int LA = 6;
  public static final int RA = 7;
  public static final int AFFECT = 28;
  public static final int RECORD = 60;
  public static final int DOUBLE_POINTS = 41;
  public static final int EQ = 25;
  public static final int BOOLEAN_LITERAL = 72;
  public static final int MOD = 39;
  public static final int CLASS = 51;
  public static final int CHARACTER_TYPE = 47;
  public static final int DOUBLE_BRACKET = 5;
  public static final int NOT_UNARY = 15;
  public static final int PLUS = 33;
  public static final int LPAR = 8;
  public static final int WHILE = 55;
  public static final int SEMIC = 40;
  public static final int DIV = 38;
  public static final int DIV_EQ = 31;
  public static final int RETURN = 52;
  public static final int ELSE = 54;
  public static final int PROCEDURE = 64;
  public static final int CONSTANTS = 56;
  public static final int STRING_LITERAL = 69;
  public static final int EQEQ = 26;
  public static final int EOF = 0;
  public static final int RPAR = 9;
  public static final int MINUS_EQ = 29;
  public static final int FUNCTION = 62;
  public static final int VARIABLE_TYPE = 42;
  public static final int REPEAT = 63;
  public static final int MAIN = 65;
  public static final int MINUS = 36;
  public static final int FLOAT_LITERAL = 71;
  public static final int ARROW_MEMORYACCESS = 3;
  public static final int IN = 50;
  public static final int OR = 18;
  public static final int error = 1;
  public static final int DIFF = 24;
  public static final int LIST = 57;
  public static final int IF = 53;
  public static final int INTEGER_TYPE = 43;
  public static final int FOREACH = 49;
  public static final int MULT_EQ = 30;
  public static final int CHARACTER_LITERAL = 68;
  public static final int RBRACKET = 11;
  public static final int RSHIFT = 17;
  public static final int AND = 14;
  public static final int STATIC = 66;
  public static final int STRUCTURE = 58;
  public static final int LBRACKET = 10;
  public static final int OR_BIT = 13;
  public static final int LSHIFT = 16;
  public static final int STRING_TYPE = 44;
}

